export type SeedItem = {
  section: string;
  module_key?: string;
  module_label?: string;
  route?: string;
  checklist_item: string;
};

const S = (section: string, module_key: string | undefined, module_label: string | undefined, route: string | undefined, items: string[]): SeedItem[] =>
  items.map((checklist_item) => ({ section, module_key, module_label, route, checklist_item }));

export const REFINEMENT_SEED: SeedItem[] = [
  ...S("Navigation & Access", undefined, undefined, "/", [
    "Sidebar shows only daily-use core tools.",
    "Revenue Command Center opens correctly.",
    "Analytics Center opens correctly.",
    "Admin Center opens correctly.",
    "Hidden modules are still accessible through hubs.",
    "Unauthorized users cannot access restricted modules.",
    "Access-denied states are clear and clean.",
    "Notification bell works without adding sidebar clutter.",
    "Mobile navigation is usable.",
    "No duplicate module links exist.",
  ]),
  ...S("End-to-End Revenue Flow", "paid_pipeline", "Paid Pipeline", "/paid-pipeline", [
    "Lead/report data appears correctly after ROAS or Attribution report is created.",
    "Leads can be sent to Paid Pipeline.",
    "Token buyer appears in Paid Pipeline.",
    "Payment can be added without errors.",
    "Lead stage can be updated.",
    "Follow-up can be created from lead.",
    "Follow-up appears in Follow-Up Command Center.",
    "Balance pending lead appears in Payment Recovery.",
    "Finance status can be updated.",
    "Final sale can be marked correctly.",
    "Audit Log records important changes.",
    "Notification is generated for important pending actions.",
    "Founder/Webinar dashboards reflect updated numbers.",
    "No duplicate leads/payments are created.",
    "Revenue flow feels clear to admin.",
  ]),
  ...S("ROAS / Reports / Attribution", "reports", "Reports & History", "/reports", [
    "ROAS Calculator opens and works.",
    "Existing API/fetched reports remain visible.",
    "Report History shows old and new reports.",
    "Daily Reporting data appears correctly.",
    "Attribution report opens correctly.",
    "Send to Paid Pipeline works.",
    "View Source Reports link works from Webinar Performance.",
    "CSV/PDF exports work.",
    "No import-sheet language appears where existing API data is used.",
    "Reports are not hidden because of missing new fields.",
    "Deleted/restored reports are handled safely.",
    "Report actions are logged in Audit Log.",
  ]),
  ...S("Calling CRM", "calling_crm", "Calling CRM", "/crm", [
    "Calling CRM opens correctly.",
    "CRM stages are clean and useful.",
    "Lead assignment works.",
    "Bulk assignment works.",
    "Admin does not appear in assignment dropdown unless explicitly eligible.",
    "Stage movement works.",
    "Notes work if available.",
    "Paid onboarding stages are clear.",
    "Send from Paid Pipeline to CRM works if applicable.",
    "CRM actions are logged in Audit Log.",
    "CRM notifications are generated only when useful.",
    "CRM filters are practical.",
  ]),
  ...S("Paid Pipeline", "paid_pipeline", "Paid Pipeline", "/paid-pipeline", [
    "Paid Pipeline opens correctly through Revenue Command Center.",
    "Main table loads quickly.",
    "Filters work properly.",
    "Add payment works.",
    "Multiple token payments work.",
    "Balance pending calculation is correct.",
    "Revenue realized calculation is correct.",
    "Final sale logic is correct.",
    "Dropped lead logic is correct.",
    "Finance partner/status fields work.",
    "Lead priority works.",
    "Owner assignment works correctly.",
    "Admin is not assignment-eligible by default.",
    "Follow-up creation works.",
    "CSV export works.",
    "Audit logs are created for important actions.",
    "Notifications are created for important pending items.",
    "Mobile view is usable.",
    "Drawer layout is clean.",
    "No duplicate payment or lead records are created.",
  ]),
  ...S("Follow-Up Command Center", "follow_up_command_center", "Follow-Up Command Center", "/follow-up-command-center", [
    "Follow-Up Command Center opens correctly.",
    "Due Today filter is accurate.",
    "Overdue filter is accurate.",
    "Missed follow-up logic is accurate.",
    "Mark Done works.",
    "Mark Done resolves related notifications.",
    "Reschedule works.",
    "Owner assignment works.",
    "WhatsApp copy works.",
    "Follow-up creation from Paid Pipeline appears here.",
    "Follow-up creation from Payment Recovery appears here.",
    "Follow-up statuses are clear.",
    "No duplicate follow-ups appear.",
    "Audit logs are created for important actions.",
    "Mobile view is usable.",
  ]),
  ...S("Payment Recovery", "payment_recovery", "Payment Recovery", "/payment-recovery", [
    "Payment Recovery opens correctly through Revenue Command Center.",
    "Active pending revenue is accurate.",
    "High-value pending filter works.",
    "No-owner pending leads are visible.",
    "No-next-payment-date leads are visible.",
    "Recovery overdue logic is accurate.",
    "Finance pending cases appear correctly.",
    "Dropped-risk cases appear correctly.",
    "Bulk owner assignment works.",
    "Bulk field update works.",
    "Follow-up creation works.",
    "Add payment works without duplicate logs.",
    "Notifications are generated correctly.",
    "Audit logs are created correctly.",
    "Payment Recovery numbers match Paid Pipeline.",
    "Mobile view is usable.",
  ]),
  ...S("Webinar Performance", "webinar_performance", "Webinar Performance", "/webinar-performance", [
    "Webinar Performance opens through Analytics Center.",
    "It uses existing reports only.",
    "No new sheet import flow appears.",
    "Refresh Existing Data works.",
    "Date filters update numbers.",
    "Registrations are accurate.",
    "Show-up numbers are accurate.",
    "Token buyers are linked from Paid Pipeline.",
    "Final sales are linked correctly.",
    "Revenue realized is accurate.",
    "Revenue to be realized is accurate.",
    "Media Buyer Quality section works.",
    "Payment Realization section works.",
    "Founder Summary copy works.",
    "Source Reports link works.",
    "Missing mapping shows a clear state.",
    "No fake/sample data appears.",
  ]),
  ...S("Master Settings", "master_settings", "Master Settings", "/master-settings", [
    "Master Settings opens through Admin Center.",
    "Business Profile saves correctly.",
    "Products/Programs save correctly.",
    "Payment models save correctly.",
    "Paid Pipeline stages save correctly.",
    "CRM stages save correctly.",
    "Follow-up reasons save correctly.",
    "Finance partners save correctly.",
    "Webinar settings save correctly.",
    "Team roles/departments save correctly.",
    "Assignment eligibility defaults save correctly.",
    "WhatsApp templates save correctly.",
    "General dropdowns save correctly.",
    "Quick-save values appear here.",
    "Settings changes reflect in relevant dropdowns.",
    "Audit logs are created for settings changes.",
    "Sensitive fields are masked.",
  ]),
  ...S("Audit Log", "audit_log", "Audit Log", "/audit-log", [
    "Audit Log opens through Admin Center.",
    "Payment added logs correctly.",
    "Payment deleted logs correctly.",
    "Stage changed logs correctly.",
    "Finance status changed logs correctly.",
    "Follow-up completed logs correctly.",
    "CRM assignment logs correctly.",
    "Master Settings changes log correctly.",
    "Access changes log correctly.",
    "Report exports/deletes log correctly.",
    "Old/new values show clearly.",
    "Sensitive fields are redacted.",
    "CSV export works.",
    "Filters work.",
    "Audit logging never blocks business actions.",
  ]),
  ...S("Notifications", "notifications", "Notifications", "/notifications", [
    "Notification bell appears and count is correct.",
    "Notifications page opens through Admin Center or bell.",
    "Refresh Notifications works.",
    "Duplicate notifications are avoided.",
    "Follow-up due alerts are generated.",
    "Follow-up overdue alerts are generated.",
    "High-value payment recovery alerts are generated.",
    "No-owner pending alerts are generated.",
    "Finance alerts are generated.",
    "Audit-based alerts are generated.",
    "Assigned user receives relevant alerts.",
    "Admin receives founder-level alerts.",
    "Mark Read works.",
    "Dismiss works.",
    "Related action links work.",
    "Notifications are useful, not noisy.",
  ]),
  ...S("Data Accuracy", undefined, undefined, undefined, [
    "Token Buyers count is accurate.",
    "Final Sales count is accurate.",
    "Revenue Realized is accurate.",
    "Revenue To Be Realized is accurate.",
    "Balance Pending is accurate.",
    "Finance Pending is accurate.",
    "Dropped leads are excluded from active pending revenue.",
    "Refunds/adjustments are handled correctly if applicable.",
    "Payment Recovery totals match Paid Pipeline totals.",
    "Webinar Performance totals match Reports + Paid Pipeline.",
    "Founder Dashboard totals match underlying modules.",
    "Date filters work consistently across modules.",
    "This Month / Last Month / Last 7 Days produce logical results.",
  ]),
  ...S("Mobile Responsiveness", undefined, undefined, undefined, [
    "Sidebar/mobile navigation works.",
    "Tables do not break layout.",
    "Drawers are usable on mobile.",
    "Cards are readable on mobile.",
    "Buttons are tappable.",
    "Filters are usable.",
    "Revenue Command Center is mobile-friendly.",
    "Admin Center is mobile-friendly.",
    "Analytics Center is mobile-friendly.",
    "No major horizontal overflow.",
  ]),
  ...S("UX / Speed / Clarity", undefined, undefined, undefined, [
    "Pages load fast.",
    "No unnecessary loading delays.",
    "Empty states are clear.",
    "Error messages are understandable.",
    "Buttons have clear labels.",
    "Critical actions have confirmation.",
    "Filters are easy to use.",
    "Tables show the right columns.",
    "Drawers do not feel cluttered.",
    "Copy summaries are useful.",
    "WhatsApp copy text is clean.",
    "No module feels confusing to navigate.",
    "No page feels visually cluttered.",
  ]),
  ...S("Final AI Insights Readiness", undefined, undefined, undefined, [
    "Paid Pipeline data is reliable.",
    "Payment Recovery data is reliable.",
    "Follow-Up data is reliable.",
    "Webinar Performance data is reliable.",
    "Notifications are reliable.",
    "Audit Log is reliable.",
    "Master Settings are stable.",
    "Founder Dashboard numbers are trusted.",
    "No critical workflow bugs remain.",
    "AI Insights can be built on top of clean data.",
  ]),
];
