project_id = "azlzgovrljdmqzghqcta"

[functions.roas-sync-source]
verify_jwt = false

[functions.roas-sync-all-sources]
verify_jwt = false

[functions.code-of-conduct-public]
verify_jwt = false

[functions.admin-team-auth]
verify_jwt = false
